apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: light-api
  namespace: default
  labels:
    app: light-api
spec:
  template:
    metadata:
      labels:
        app: light-api
    spec:
      containers:
        - image: derry369/light-api:phase2-coldstart
          name: light-api
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "light-api"