apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: long-task
  namespace: default
  labels:
    app: long-task
spec:
  template:
    metadata:
      labels:
        app: long-task
    spec:
      containers:
        - image: derry369/long-task:phase2-coldstart
          name: long-task
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "long-task"