apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-inference
  namespace: default
  labels:
    app: ml-inference
spec:
  template:
    metadata:
      labels:
        app: ml-inference
    spec:
      containers:
        - image: derry369/ml-inference:phase2-import
          name: ml-inference
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "ml-inference"