apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-processor
  namespace: default
  labels:
    app: data-processor
spec:
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
        - image: derry369/data-processor:phase2-coldstart
          name: data-processor
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "data-processor"